name: Check

on:
  - push
  - pull_request

jobs:
  linter:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags') }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run
        run: tox -e linter
