name: Check

on:
  - push
  - pull_request

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags') }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run
        run: tox -e linter

  markdownlint:
    # https://github.com/marketplace/actions/markdown-lint
    name: markdownlint
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: articulate/actions-markdownlint@v1.1.0
        with:
          config: .markdownlint-config.yaml
        #   files: 'docs/**/*.md'
        #   ignore: node_modules
        #   version: 0.28.1
