# Based on https://fedoramagazine.org/github-actions-use-podman-to-run-fedora-linux/

name: CI
on:
  pull_request:

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"

    steps:
      - name: Get source
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox -e py

  bootstrap:
    name: bootstrap
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"

    steps:
      - name: Get source
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: ./e2e/test_bootstrap.sh

  # e2e:
  #   name: e2e
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version:
  #         - "3.9"
  #         - "3.12"
  #       test-script:
  #         - e2e/test_rebuild_following_bootstrap.sh

  #   steps:
  #     - name: Get source
  #       uses: actions/checkout@v4

  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Setup Podman
  #       run: |
  #         sudo apt update
  #         sudo apt-get -y install podman
  #         podman pull fedora:39

  #     - name: Run tests
  #       run: |
  #         PYTHON=python${{ matrix.python-version }} ${{ matrix.test-script }}
