name: CI
on:
  pull_request:

jobs:
  test:
    name: fedora
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.12"

    steps:
      - name: Get source
        uses: actions/checkout@v4

      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:39

      - name: Create container and run tests
        run: |
          echo ${{ matrix.python-version }}
          ls -a
