# Based on https://fedoramagazine.org/github-actions-use-podman-to-run-fedora-linux/

name: CI
on:
  pull_request:

jobs:
  test:
    name: fedora
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.12"

    steps:
      - name: Get source
        uses: actions/checkout@v4

      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:39

      - name: Create container
        run: |
          podman build --tag test-${{ matrix.python-version }} -f ./Containerfile

      - name: Run tests
        run: |
          podman run --rm \
            --userns=keep-id \
            --security-opt label=disable \
            --volume .:/src:rw,exec \
            -e PYTHON_TO_TEST=python${{ matrix.python-version }} \
            test-${{ matrix.python-version }} \
            ./test.sh
